### ISSUE TITLE
Need to tidy up code formatting 

### ISSUE THREAD

**Issue by proyb6** [joonlabs/php-graphql#1]
I see some inconsistant with **{** formatting, tidy up your code for readability.

**Comment by joonlabs** [comment]
@proyb6 thanks for your feedback. Assuming you mean things like [src/Errors/GraphQLError.php#L36](https://github.com/joonlabs/php-graphql/blob/dceb2a01b1fda244c0ca0148df4c3d92bd35a630/src/Errors/GraphQLError.php#L36) we reviewed all files and fixed the issues.
