### ISSUE TITLE
Test and Doc?

### ISSUE THREAD

**Issue by proyb6** [joonlabs/php-graphql#2]
Most projects should have a marketing site along with test suite, documentations, benchmarks and why this is useful, thanks to other suggestion on Reddit.

**Comment by joonlabs** [comment]
hey @proyb6 thank for your feedback. Tests and docs already added. Updated README and benchmarks are following. Keeping this issue up until then.

**Comment by joonlabs** [comment]
README is updated now. Package installable via composer. Documentation available under https://joonlabs.github.io/php-graphql/.

**Comment by joonlabs** [comment]
Benchmarks are available now (see v1.0.3). Closing this issue. Thanks for your help 🙏
