### ISSUE TITLE
Closing PHP Tags

### ISSUE THREAD

**Issue by javabudd** [joonlabs/php-graphql#3]
https://www.php.net/manual/en/language.basic-syntax.phptags.php

**Comment by AlexKapustin** [comment]
Emh, sorry, but what's the issue with closing tags exactly?

**Comment by javabudd** [comment]
Coming from the docs:

> If a file contains only PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.

**Comment by joonlabs** [comment]
@javabudd thanks for your feedback, you're absolutely right. We reviewed all files and fixed this issue in commit 7e3327f.
